apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: podinfo-failover
  labels:
    failover.linkerd.io/controlled-by: linkerd-failover
  annotations:
    failover.linkerd.io/primary-service: podinfo
spec:
  service: podinfo
  backends:
  - service: podinfo-east
    weight: 50
  - service: podinfo
    weight: 50
