apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
data:
 nginx.conf: |-
  pid /tmp/pid;
  error_log stderr;
  events {}
  http {
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    server {
      listen 8080;
      set $east "east";
      set $west "west";
      resolver kube-dns.kube-system.svc.west.k3d.example.com;

      location / {
        proxy_pass http://podinfo.test.svc.west.k3d.example.com:9898/;
        proxy_http_version 1.1;
      }
      location /east {
        proxy_pass http://podinfo-$east.test.svc.east.k3d.example.com:9898/;
        proxy_http_version 1.1;
      }
      location /west {
        proxy_pass http://podinfo-$west.test.svc.west.k3d.example.com:9898/;
        proxy_http_version 1.1;
      }
    }
  }
---
